spec:
  type: NodePort
  ports:
  - name: status-port
    nodePort: 30002
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30001
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tcp
    nodePort: 31801
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 30130
    port: 15443
    protocol: TCP
    targetPort: 15443

